# ShardingSphere 5.x 配置
spring:
  shardingsphere:
    mode:
      type: Memory
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-2ze66cjk287xy3e57wo.mysql.rds.aliyuncs.com:3306/db1?useUnicode=true&characterEncoding=UTF-8
        username: eudon
        password: Eudon061618
    props:
      sql-show: false
