spring:
  main:
    allow-bean-definition-overriding: false
  cloud:
    zookeeper:
      connect-string: 47.95.203.22:2181
      session-timeout: 30000
      connection-timeout: 3000
      retry:
        max-retries: 5
        initial-interval: 1000
        max-interval: 5000
      enabled: true
      config:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.apache.zookeeper: info
    org.apache.curator: info
    com.eudon.common.zookeeper.monitor: debug
